### ISSUE TITLE
example site down?

### ISSUE THREAD

**Issue by stacktoshi** [studiokaiji/nostr-webhost#61]
<img width="971" alt="Screenshot 2024-01-31 at 1 41 20 PM" src="https://github.com/studiokaiji/nostr-webhost/assets/137957101/e7aa47b0-3a82-46dd-ae12-7c33d7fe8da5">

Also, how does this host SPAs on nostr?

**Comment by studiokaiji** [comment]
The site has been restored. Thank you for your report.

**Comment by studiokaiji** [comment]
> Also, how does this host SPAs on nostr?

HTML, CSS, and JS codes are posted as Nostr events on the relay, and the web server reads them and returns them to the browser.
